#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Oct 06 13:44:15 IST 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_demux_32_to_1_behav -key {Behavioral:sim_1:Functional:tb_demux_32_to_1} -tclbatch tb_demux_32_to_1.tcl -view /home/itzzinfinity/Cozy Drive/100daysofRTL/day_030/project_1/tb_demux_32_to_1_behav.wcfg -log simulate.log"
xsim tb_demux_32_to_1_behav -key {Behavioral:sim_1:Functional:tb_demux_32_to_1} -tclbatch tb_demux_32_to_1.tcl -view /home/itzzinfinity/Cozy Drive/100daysofRTL/day_030/project_1/tb_demux_32_to_1_behav.wcfg -log simulate.log

