#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Sep 29 17:27:16 IST 2024
# SW Build 5076996 on Wed May 22 18:36:09 MDT 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim parallel_add_sub_tb_behav -key {Behavioral:sim_1:Functional:parallel_add_sub_tb} -tclbatch parallel_add_sub_tb.tcl -view /home/itzzinfinity/Cozy Drive/100daysofRTL/day_009/project_1/parallel_add_sub_tb_behav.wcfg -log simulate.log"
xsim parallel_add_sub_tb_behav -key {Behavioral:sim_1:Functional:parallel_add_sub_tb} -tclbatch parallel_add_sub_tb.tcl -view /home/itzzinfinity/Cozy Drive/100daysofRTL/day_009/project_1/parallel_add_sub_tb_behav.wcfg -log simulate.log

